# Generated by Django 4.1 on 2022-08-12 06:52

import common.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.constants
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFriendship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("modify_date", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    common.fields.EnumField(
                        default="REQUESTED", enum=user.constants.UserFriendshipState
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="senders",
                        to="user.user",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receivers",
                        to="user.user",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="userfriendship",
            constraint=models.UniqueConstraint(
                fields=("sender_id", "receiver_id"), name="exclusive friendship request"
            ),
        ),
    ]
