version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=wish-list
      - POSTGRES_PASSWORD=notsecretpass
      - POSTGRES_DB=wish-list
    ports:
      - '5432:5432'
    volumes: 
      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=wish-list
      - POSTGRES_USER=wish-list
      - POSTGRES_PASSWORD=notsecretpass
    depends_on:
      - db