version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=wish-list
      - POSTGRES_PASSWORD=notsecretpass
      - POSTGRES_DB=wish-list
    ports:
      - '5432:5432'
    volumes: 
      - ./data/db:/var/lib/postgresql/data

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
     - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    ports:
     - "9092:9092"
    expose:
     - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "GENERAL:1:1"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  celery:
    build: .
    command: celery -A celeryapp.app worker  -l INFO
    environment:
      - REDIS_HOST=redis
      - KAFKA_HOST=kafka
      - POSTGRES_NAME=wish-list
      - POSTGRES_USER=wish-list
      - POSTGRES_PASSWORD=notsecretpass
      - POSTGRES_HOST=db
    volumes:
      - .:/code
    working_dir: /code/src
    depends_on:
      - db
      - redis
      - kafka

  celery-beat:
    build: .
    volumes:
      - .:/code
    working_dir: /code/src
    command: celery -A celeryapp.app beat -l INFO
    environment:
      - REDIS_HOST=redis
      - KAFKA_HOST=kafka
      - POSTGRES_NAME=wish-list
      - POSTGRES_USER=wish-list
      - POSTGRES_PASSWORD=notsecretpass
      - POSTGRES_HOST=db
    depends_on:
      - db
      - redis
      - kafka
  
  web:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=wish-list
      - POSTGRES_USER=wish-list
      - POSTGRES_PASSWORD=notsecretpass
      - POSTGRES_HOST=db
      - KAFKA_HOST=kafka
      - REDIS_HOST=redis
    depends_on:
      - db
      - kafka
      - zookeeper