# Generated by Django 4.1 on 2022-08-10 14:45

import common.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import wishes.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WishItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('state', common.fields.EnumField(default='OPEN', enum=wishes.constants.WishItemStatus)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishes.wishlist')),
                ('to_be_gifted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
